/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.sql.SQLException;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import trandpl.dao.UserDAO;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.HrPojo;

/**
 *
 * @author ashut
 */
public class AdminModifyHrFrame extends javax.swing.JFrame {

    private String password;
    private Map<String,HrPojo> allHr;
    
    public AdminModifyHrFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Admin Modify HR Frame");
        lblName.setText(CurrentUser.getName());
        loadHrDetails();
    }
    private boolean validateInputs(){
        char[] pwd=txtPassword.getPassword();
        char[] repwd=txtCnfrmPwd.getPassword();
        if(pwd.length<4||repwd.length<4){
            JOptionPane.showMessageDialog(null,"Passwords Must Be Atleat 4 Character Long!");
            return false;
        }
        password=String.valueOf(pwd);
        String repassword=String.valueOf(repwd);
        if(password.equals(repassword)==false){
            JOptionPane.showMessageDialog(null,"Passwords do not match!");
            return false;
        }
        return true;
    }
    private void clearAll(){
        
        txtPassword.setText("");
        txtCnfrmPwd.setText("");
        jcAllUserId.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHrId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        txtCnfrmPwd = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        btnModifyHr = new javax.swing.JButton();
        lblHrName = new javax.swing.JLabel();
        JTextField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jcAllUserId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 192, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 964, 144));

        btnLogOut.setBackground(new java.awt.Color(173, 192, 234));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 124, 41));

        btnBack.setBackground(new java.awt.Color(173, 192, 234));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 134, 42));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        jLabel4.setText("Welcome ,");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 108, 42));

        lblName.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 281, 42));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modify-emp.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel7.setText("User Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 98, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel8.setText("Hr Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 149, 30));

        txtHrId.setBackground(new java.awt.Color(173, 192, 234));
        txtHrId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtHrId.setBorder(null);
        jPanel1.add(txtHrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 300, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 350, 60));

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel14.setText("New Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 150, 30));

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel15.setText("Confirm Password");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 220, 30));

        txtPassword.setBackground(new java.awt.Color(172, 192, 234));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 290, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 350, 40));

        txtCnfrmPwd.setBackground(new java.awt.Color(172, 194, 234));
        txtCnfrmPwd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtCnfrmPwd.setBorder(null);
        txtCnfrmPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnfrmPwdActionPerformed(evt);
            }
        });
        jPanel1.add(txtCnfrmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 280, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TextFieldPic.png"))); // NOI18N
        jLabel17.setText("\n");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 350, 40));

        btnModifyHr.setBackground(new java.awt.Color(173, 192, 234));
        btnModifyHr.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnModifyHr.setText("Modify Changes Of HR");
        btnModifyHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyHrActionPerformed(evt);
            }
        });
        jPanel1.add(btnModifyHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 240, 50));

        lblHrName.setBackground(new java.awt.Color(243, 246, 254));
        lblHrName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.add(lblHrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 180, 30));

        JTextField.setBackground(new java.awt.Color(243, 246, 254));
        JTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JTextField.setText("Hr Name -");
        JTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 310, 50));

        jTextField2.setBackground(new java.awt.Color(243, 246, 254));
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 930, 20));

        jcAllUserId.setBackground(new java.awt.Color(243, 246, 254));
        jcAllUserId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcAllUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAllUserIdActionPerformed(evt);
            }
        });
        jPanel1.add(jcAllUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 310, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminHrModuleFrame af=new AdminHrModuleFrame();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCnfrmPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnfrmPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnfrmPwdActionPerformed

    private void btnModifyHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyHrActionPerformed
        // TODO add your handling code here:
        //System.out.println(validateInputs());
       if(!validateInputs()){
           return;
       }
       try
       {
           boolean result=UserDAO.updatePwd(jcAllUserId.getSelectedItem().toString(), password);
           if(result){
               JOptionPane.showMessageDialog(null,"Password Changed Successfully","Done!",JOptionPane.INFORMATION_MESSAGE);
           }
           else{
               JOptionPane.showMessageDialog(null,"Sorry! Could Not change the password","Unsuccessfull!",JOptionPane.ERROR_MESSAGE);
           }
           clearAll();
       }
       catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnModifyHrActionPerformed

    private void jcAllUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAllUserIdActionPerformed
        String userId=(String)jcAllUserId.getSelectedItem();
        HrPojo hr=allHr.get(userId);
        txtHrId.setText(hr.getHrId());
        lblHrName.setText(hr.getHrName());
        
    }//GEN-LAST:event_jcAllUserIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModifyHrFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModifyHr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jcAllUserId;
    private javax.swing.JLabel lblHrName;
    private javax.swing.JLabel lblName;
    private javax.swing.JPasswordField txtCnfrmPwd;
    private javax.swing.JTextField txtHrId;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void loadHrDetails() {
        try
        {
            allHr=UserDAO.getAllHrList();
            Set <String> keys=allHr.keySet();
            for(String userId:keys){
                jcAllUserId.addItem(userId);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
}
